version: "3"
services:
  api-server:
    container_name: udemy-nestjs
    build: .
    tty: true
    ports:
      - 8080:3000
    volumes:
      - .:/work/udemy-nestjs
      - node_modules:/work/udemy-nestjs/node_modules
volumes:
  node_modules: